version: '3'
services:
  
  #PHP Service
  app:
    build:
      args:
        - user=v4mpc
        - uid=1000
      context: .
      dockerfile: Dockerfile
    image: mauzo
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - /Users/v4mpc/repo/Mauzo:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:1.17
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"

    volumes:
      - /Users/v4mpc/repo/Mauzo:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - app-network

  #MySQL Service
  db:
    image:  mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mauzo
      MYSQL_ROOT_PASSWORD: mauzo
      MYSQL_PASSWORD: mauzo
      MYSQL_USER: mauzo
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
